
---

title: "Clemz Clemz Academy" baseurl: "/Clemz-Student-Scoreboard"  # Keep this if it's a project site url: "https://clemzclems.github.io"  # GitHub Pages base URL markdown: kramdown theme: minima  # Optional, but good to specify a theme layout: default permalink: /contact/

<h1>Contact Clemz Clemz Academy</h1><form action="https://formspree.io/f/mwpvdgeo" method="POST">
    <label for="name">Name:</label>
    <input type="text" id="name" name="name" required><label for="email">Email:</label>
<input type="email" id="email" name="email" required>

<label for="message">Message:</label>
<textarea id="message" name="message" required></textarea>

<button type="submit">Send</button>

</form><h2>Connect with Me</h2>
<ul>
    <li><a href="https://facebook.com/ClemzClems" target="_blank">Facebook</a></li>
    <li><a href="https://instagram.com/clemzclems" target="_blank">Instagram</a></li>
    <li><a href="https://youtube.com/@mathcraft3d?si=lhlfJLoWjQb810PN" target="_blank">YouTube</a></li>
</ul><h2>Payment Details</h2>
<ul>
    <li><strong>First Bank Account:</strong> Elimian Clement, Ehinomen</li>
    <li><strong>Account Number:</strong> 3061816508</li>
    <li><strong>Bank:</strong> First Bank</li>
    <li><strong>PayPal:</strong> <a href="https://paypal.me/clemzclems?country.x=AE&locale.x=en_US" target="_blank">Donate via PayPal</a></li>
</ul>
